twig:
    globals:
      eccube_config: '@Eccube\Common\EccubeConfig'
    paths:
      '%kernel.project_dir%/src/Eccube/Resource/template/install': ~
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
